language: php



before_script:
    - make install


script:
    - make check
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"
    urls:
        # canax
        - https://webhooks.gitter.im/e/6e4660b0024de67de0af
        # canax anax-cli
        - https://webhooks.gitter.im/e/14ed14c6149187b9dcc7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
