language: php



before_script:
    - make install install-dev


script:
    - make check
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"
    urls:
        - https://webhooks.gitter.im/e/6fa4dd34a8c48baec932
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
