version: "3"

services:

  bats:
    #image: bats/bats:latest
    build:
      context: .docker/bats
      dockerfile: Dockerfile
    volumes:
      - .:/code

  dbw:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - .:/mnt
